and pewdiepie saw that it was good

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+[ ! -f "utils" ] && echo "Missing: utils" && exit 1
+source ./utils
+
+[ ! -f "packages" ] && echo "Missing: packages" && exit 1
+source ./packages
+
 mv ~/.config ~/.old_config
 mv ~/.local ~/.old_local
 
@@ -12,29 +18,27 @@ mkdir -p ~/.config
 mkdir -p ~/.local/share/zsh
 mkdir -p ~/.local/share/mpd
 
-git clone http://aur.archlinux.org/paru-bin.git
-cd paru-bin
-makepkg -si --noconfirm
-cd ..
-rm -rf paru-bin
+if ! command -v paru &> /dev/null; then
+	git clone http://aur.archlinux.org/paru-bin.git >/dev/null 2>&1
+	cd paru-bin
+	makepkg -si --noconfirm >/dev/null 2>&1
+	cd ..
+	rm -rf paru-bin
+fi
 
-paru --noconfirm -Syu
+paru --noconfirm -Syu >/dev/null 2>&1
 
-paru -S --noconfirm hyprland hypridle hyprlock hyprshot hyprpicker \ 
-	waybar dunst wl-clipboard mpv imv fuzzel power-profiles-daemon \
-	xdg-desktop-portal-gtk xdg-desktop-portal-hyprland mesa-vdpau \
-	libva-mesa-driver vulkan-radeon bluez bluez-utils \
-	swaybg ttf-jetbrains-mono ttf-nerd-fonts-symbols
+echo "Installing packages..."
+install_packages "${ARCH[@]}"
 
-paru -S --noconfirm zsh alacritty tmux btop neovim yazi ripgrep fd \
-	fzf zip unzip 7zip stow bluetui ncmpcpp mpd mpc man-db flatpak 
+echo "Installing flatpaks..."
+install_flatpaks "${FLATPAKS[@]}"
 
 stow --no-folding --adopt --target=$HOME/.config config
 stow --no-folding --adopt --target=$HOME/.local local
 ln -s /usr/share/themes ~/.local/share/themes
 ln -s /usr/share/icons ~/.local/share/icons
 
-sudo systemctl --user mask backlight@.service
 sudo systemctl enable seatd.service
 sudo systemctl enable bluetooth.service
 sudo systemctl enable power-profiles-daemon.service
@@ -49,5 +53,6 @@ flatpak override --user --env=XCURSOR_THEME=Adwaita
 flatpak override --user --env=XCURSOR_SIZE=24
 flatpak override --user --socket=wayland
 
-sudo ./system $USER
+root_setup "$USER"
+
 chsh -s /bin/zsh
